import { IconName } from '@/components/shared/Icon';

export interface ToolEntry {
  id: string; // Dynamic URL slug matching the folder name
  name: string; // Human display name
  description: string; // Short UI description
  category: 'pdf' | 'image' | 'developer' | 'text' | 'calculator' | 'converter';
  tags: string[]; // Search tags/aliases
  keywords: string[]; // Meta tags
  icon: IconName;
  seoTitle: string; // SEO page title
  seoDescription: string; // SEO meta description
  relatedTools: string[]; // Related tool IDs for recommendations
  requirements: {
    browser: boolean;
    server: boolean;
  };
  addedAt: string; // ISO date string (YYYY-MM-DD)
  status: 'draft' | 'planned' | 'in-development' | 'testing' | 'published' | 'maintenance';
}

export const TOOLS_REGISTRY: ToolEntry[] = [
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate RFC4122 version 4 compliant universally unique identifiers (UUIDs) locally.',
    category: 'developer',
    tags: ['uuid', 'guid', 'generator', 'random', 'unique', 'rfc4122'],
    keywords: ['uuid generator', 'generate uuid', 'guid generator', 'random uuid', 'online uuid'],
    icon: 'Fingerprint',
    seoTitle: 'Free Client-Side UUID & GUID Generator',
    seoDescription: 'Generate RFC4122 v4 compliant universally unique identifiers (UUIDs) or GUIDs locally in your browser. Complete data privacy.',
    relatedTools: ['base64-converter', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-25',
    status: 'published',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Pretty-print, validate, minify, and check syntax of your JSON code.',
    category: 'developer',
    tags: ['json', 'formatter', 'pretty print', 'minify', 'validator', 'beautify'],
    keywords: ['json formatter', 'pretty print json', 'format json online', 'minify json', 'validate json'],
    icon: 'Braces',
    seoTitle: 'Free Client-Side JSON Formatter & Beautifier',
    seoDescription: 'Pretty-print, minify, and validate JSON code securely in your web browser. Zero server uploads for complete data privacy.',
    relatedTools: ['uuid-generator', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-01',
    status: 'published',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Analyze word count, character size, read time, and text stats in real-time.',
    category: 'text',
    tags: ['word count', 'character count', 'analyzer', 'text stats', 'casing'],
    keywords: ['word counter', 'character counter', 'word count online', 'character size analyzer'],
    icon: 'CaseSensitive',
    seoTitle: 'Free Online Word Counter - Analyze Text & Character Size',
    seoDescription: 'Count words, characters, sentences, paragraphs, and read times. Secure, in-browser analysis with no data logged.',
    relatedTools: ['uuid-generator', 'password-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-10',
    status: 'published',
  },
  {
    id: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Convert text, strings, and images into Base64 format and back.',
    category: 'developer',
    tags: ['base64', 'encode', 'decode', 'converter', 'string', 'binary'],
    keywords: ['base64 encoder', 'base64 decoder', 'base64 encode online', 'base64 convert string'],
    icon: 'Binary',
    seoTitle: 'Free Client-Side Base64 Encoder & Decoder',
    seoDescription: 'Encode and decode Base64 strings and files safely. 100% browser-based calculations protect sensitive tokens.',
    relatedTools: ['uuid-generator', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-15',
    status: 'published',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL parameters safely and instantly.',
    category: 'developer',
    tags: ['url', 'encode', 'decode', 'uri', 'parameter', 'percent-encoding'],
    keywords: ['url encoder', 'url decoder', 'urlencode online', 'decode url parameter'],
    icon: 'RefreshCw',
    seoTitle: 'Free Client-Side URL Parameter Encoder & Decoder',
    seoDescription: 'Encode and decode URL parameters or URI strings securely in your browser tab. Instant offline client-side conversions.',
    relatedTools: ['json-formatter', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-27',
    status: 'published',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate highly secure custom passwords locally using custom strength rules.',
    category: 'developer',
    tags: ['password', 'generator', 'security', 'random string', 'passphrase'],
    keywords: ['password generator', 'random password', 'generate secure password', 'online password maker'],
    icon: 'Lock',
    seoTitle: 'Free Client-Side Secure Password Generator',
    seoDescription: 'Generate secure, randomized passwords locally in your browser. Configure character rules, lengths, and avoid server storage logs.',
    relatedTools: ['uuid-generator', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-27',
    status: 'published',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JSON Web Tokens (JWT) locally to view header, payload, and claim dates.',
    category: 'developer',
    tags: ['jwt', 'token', 'decoder', 'json web token', 'payload'],
    keywords: ['jwt decoder', 'decode jwt online', 'jwt payload viewer', 'jwt header'],
    icon: 'Key',
    seoTitle: 'Free Client-Side JWT Decoder & Viewer',
    seoDescription: 'Decode JSON Web Tokens (JWT) locally in your browser. View header, payload claims, expiration states, and signature components securely.',
    relatedTools: ['uuid-generator', 'json-formatter', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes locally.',
    category: 'developer',
    tags: ['hash', 'crypto', 'sha256', 'md5', 'sha512', 'checksum'],
    keywords: ['hash generator', 'md5 hash generator', 'sha256 online generator', 'generate hash locally'],
    icon: 'Hash',
    seoTitle: 'Free Client-Side MD5, SHA-256 & SHA-512 Hash Generator',
    seoDescription: 'Calculate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 cryptographic hashes or checksums securely in your browser using Web Crypto APIs.',
    relatedTools: ['uuid-generator', 'base64-converter', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text casing style between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, and other formats locally.',
    category: 'text',
    tags: ['case converter', 'text casing', 'uppercase', 'lowercase', 'camelcase', 'pascalcase', 'slugify'],
    keywords: ['case converter', 'convert text case', 'slugify string online', 'uppercase lowercase converter'],
    icon: 'CaseSensitive',
    seoTitle: 'Free Client-Side Text Case Converter - UPPERCASE, camelCase & PascalCase',
    seoDescription: 'Convert your text casing style between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case securely in your browser tab.',
    relatedTools: ['word-counter', 'uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Clean list data by removing duplicate lines. Supports case sensitivity filters, sorting, and whitespace trimming.',
    category: 'text',
    tags: ['duplicate lines', 'remove duplicates', 'deduplicate list', 'sort list', 'unique list'],
    keywords: ['remove duplicate lines', 'deduplicate list online', 'remove repeating lines', 'clean text list'],
    icon: 'Layers',
    seoTitle: 'Free Client-Side List Deduplicator - Remove Duplicate Lines',
    seoDescription: 'Clean your list data by removing duplicate lines securely in your browser. Configure case-sensitive compares, whitespace trims, and alphabetical sorting.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate custom placeholder text in words, sentences, or paragraphs formatted as plain text or HTML.',
    category: 'text',
    tags: ['lorem ipsum', 'placeholder text', 'dummy text', 'text generator', 'html generator'],
    keywords: ['lorem ipsum generator', 'generate placeholder text', 'dummy paragraph creator', 'free lorem text'],
    icon: 'Type',
    seoTitle: 'Free Client-Side Lorem Ipsum Placeholder Text Generator',
    seoDescription: 'Generate custom dummy text in words, sentences, or paragraphs, formatted as plain text or HTML paragraph tags securely in your browser tab.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Increase productivity using the Pomodoro technique. Keep focus, manage breaks, and track your daily sessions locally.',
    category: 'calculator',
    tags: ['pomodoro', 'timer', 'focus timer', 'productivity timer', 'pomodoro technique', 'time management'],
    keywords: ['pomodoro timer', 'online pomodoro', 'focus countdown', 'productivity timer online', 'pomodoro clock'],
    icon: 'Hourglass',
    seoTitle: 'Free Client-Side Pomodoro Focus Timer - Boost Productivity',
    seoDescription: 'Boost your focus and time management using the Pomodoro technique. Custom focus slots, short/long breaks, fullscreen countdown mode, alerts, and browser notifications.',
    relatedTools: ['word-counter', 'uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate duration between dates or add/subtract calendar days.',
    category: 'calculator',
    tags: ['date', 'time duration', 'calendar calculator', 'days between dates'],
    keywords: ['date calculator', 'calculate days between dates', 'add days to date', 'calendar duration calculator'],
    icon: 'Calendar',
    seoTitle: 'Free Online Date & Time Calculator',
    seoDescription: 'Calculate the exact number of days, weeks, months, or years between two calendar dates, or add/subtract days in your browser.',
    relatedTools: ['uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-20',
    status: 'planned',
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Merge multiple PDF files into a single combined document locally.',
    category: 'pdf',
    tags: ['pdf', 'merge', 'combine', 'join pdf', 'pdf merger', 'local pdf'],
    keywords: ['pdf merge', 'combine pdf files', 'merge pdf online', 'join pdfs locally', 'pdf joiner free'],
    icon: 'Combine',
    seoTitle: 'Free Client-Side PDF Merge - Combine PDF Documents Securely',
    seoDescription: 'Combine multiple PDF files into a single document client-side in your web browser. Drag to reorder pages. Complete data privacy.',
    relatedTools: ['pdf-split', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    description: 'Split PDF files, extract page ranges, or export individual pages locally.',
    category: 'pdf',
    tags: ['pdf', 'split', 'extract', 'pdf page extractor', 'pdf splitter', 'cut pdf'],
    keywords: ['pdf split', 'extract pdf pages', 'split pdf online', 'pdf splitter free', 'cut pdf pages locally'],
    icon: 'Scissors',
    seoTitle: 'Free Client-Side PDF Split - Extract PDF Pages Securely',
    seoDescription: 'Split PDF files by pages, extract specific ranges, or export single pages locally in your browser. 100% private, no uploads.',
    relatedTools: ['pdf-merge', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert and compile JPG, PNG, and WebP images into a single PDF document.',
    category: 'pdf',
    tags: ['pdf', 'images to pdf', 'jpg to pdf', 'png to pdf', 'convert images to pdf'],
    keywords: ['images to pdf', 'jpg to pdf online', 'png to pdf converter', 'compile images to pdf', 'convert jpg to pdf locally'],
    icon: 'FileImage',
    seoTitle: 'Free Client-Side Images to PDF Converter - Convert PNG/JPG Securely',
    seoDescription: 'Convert PNG, JPG, and WebP images into a single PDF document. Drag to arrange pages, fully offline browser compilation.',
    relatedTools: ['pdf-merge', 'pdf-split'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    description: 'Compress and optimize PDF file sizes locally inside your browser memory using hybrid rasterization.',
    category: 'pdf',
    tags: ['pdf', 'compress', 'reduce size', 'pdf shrinker', 'optimize pdf'],
    keywords: ['pdf compress', 'reduce pdf size', 'pdf size shrinker', 'compress pdf locally', 'optimize pdf size browser'],
    icon: 'Layers',
    seoTitle: 'Free Client-Side PDF Compressor - Reduce PDF Size Securely',
    seoDescription: 'Compress and optimize PDF file sizes locally in your browser using Ghostscript WebAssembly. 100% private, no files uploaded.',
    relatedTools: ['pdf-merge', 'pdf-split'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-30',
    status: 'published',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress and reduce sizes of PNG, JPG, and WebP images offline.',
    category: 'image',
    tags: ['image', 'compress', 'minify image', 'reduce image size', 'jpg compressor'],
    keywords: ['image compressor', 'reduce image size online', 'compress jpeg', 'png compressor', 'shrink image locally'],
    icon: 'Layers',
    seoTitle: 'Free Client-Side Image Compressor - Reduce Image Sizes Securely',
    seoDescription: 'Compress PNG, JPEG, and WebP images client-side. Slider controls for quality and max dimensions. Complete data privacy.',
    relatedTools: ['image-resizer', 'image-format-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize image dimensions in pixels or percentages maintaining aspect ratios.',
    category: 'image',
    tags: ['image', 'resize', 'scale image', 'change dimensions', 'image scaler'],
    keywords: ['image resizer', 'resize image dimensions', 'scale photo online', 'resize picture locally'],
    icon: 'Sliders',
    seoTitle: 'Free Client-Side Image Resizer - Adjust Dimensions Securely',
    seoDescription: 'Adjust width and height dimensions of your image files locally. Aspect ratio lock support, fully offline execution.',
    relatedTools: ['image-compressor', 'image-format-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'image-format-converter',
    name: 'Image Format Converter',
    description: 'Convert image files between JPG, PNG, and WebP formats.',
    category: 'image',
    tags: ['image converter', 'format converter', 'png to jpg', 'jpg to webp', 'convert image'],
    keywords: ['image format converter', 'png to jpg online', 'convert jpg to webp', 'change image format locally'],
    icon: 'RefreshCw',
    seoTitle: 'Free Client-Side Image Format Converter - PNG, JPG & WebP',
    seoDescription: 'Convert image formats between JPG, PNG, and WebP locally in your browser. Supports multiple file batches.',
    relatedTools: ['image-compressor', 'image-resizer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop and trim image files to custom areas using adjustable offsets.',
    category: 'image',
    tags: ['image', 'crop', 'trim image', 'cut image', 'photo cropper'],
    keywords: ['image cropper', 'crop photo online', 'trim image boundaries', 'cut picture locally'],
    icon: 'Crop',
    seoTitle: 'Free Client-Side Image Cropper - Cut & Trim Photos Securely',
    seoDescription: 'Crop image files to custom pixel dimensions or aspects locally. Bounded offset adjustments, fully client-side canvas render.',
    relatedTools: ['image-compressor', 'image-resizer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'fullscreen-clock',
    name: 'Fullscreen Digital Clock',
    description: 'A beautiful digital clock for study desks, workspaces, and fullscreens.',
    category: 'converter',
    tags: ['clock', 'digital clock', 'fullscreen clock', 'desk clock', 'time display'],
    keywords: ['fullscreen clock', 'digital clock online', 'desk study clock', 'large time display screen'],
    icon: 'Clock',
    seoTitle: 'Free Online Fullscreen Digital Clock - Work & Study Timer',
    seoDescription: 'A beautiful, customizable fullscreen digital clock for desk displays. Toggle 12/24 hour views, seconds, dates, and fullscreen modes.',
    relatedTools: ['stopwatch', 'countdown-timer', 'pomodoro-timer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    description: 'High-precision lap-capable stopwatch for tracking performance and milestones.',
    category: 'converter',
    tags: ['stopwatch', 'laps', 'timer', 'split timer', 'precision timer'],
    keywords: ['stopwatch online', 'precision stopwatch', 'lap timer', 'milestone tracker free'],
    icon: 'Stopwatch',
    seoTitle: 'Free Online Stopwatch - Precision Lap Timer',
    seoDescription: 'Track elapsed time with sub-millisecond precision. Record splits and lap milestones in a scrollable list, fully client-side.',
    relatedTools: ['fullscreen-clock', 'countdown-timer', 'pomodoro-timer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Set countdown alarms with custom audio notifications when reaching zero.',
    category: 'converter',
    tags: ['countdown', 'timer', 'alarm', 'clock', 'countdown alarm'],
    keywords: ['countdown timer', 'countdown alarm online', 'set timer sound', 'countdown clock free'],
    icon: 'Timer',
    seoTitle: 'Free Online Countdown Timer with Audio Alarm',
    seoDescription: 'Configure countdown timers with hours, minutes, and seconds. Plays synthesized audio chime alarms entirely locally on completion.',
    relatedTools: ['fullscreen-clock', 'stopwatch', 'pomodoro-timer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate customizable QR Codes for URLs and text inputs.',
    category: 'converter',
    tags: ['qr', 'qr code', 'generator', 'encode qr', 'make qr code'],
    keywords: ['qr code generator', 'create qr code online', 'custom qr creator', 'generate qr locally'],
    icon: 'QrCode',
    seoTitle: 'Free Client-Side QR Code Generator - Customize Colors & Sizes',
    seoDescription: 'Generate custom QR codes from URLs or texts locally. Configure foreground and background colors, and download as high-res PNG.',
    relatedTools: ['barcode-generator', 'color-picker'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate CODE128, EAN13, EAN8, and UPC barcodes as vector SVGs.',
    category: 'converter',
    tags: ['barcode', 'generator', 'code128', 'ean13', 'upc', 'vector barcode'],
    keywords: ['barcode generator', 'create barcode online', 'code128 creator', 'generate barcode svg'],
    icon: 'Barcode',
    seoTitle: 'Free Client-Side Barcode Generator - Vector SVGs',
    seoDescription: 'Generate retail and industrial barcodes (CODE128, EAN13, EAN8, UPC) locally in your browser. Download as scalable vector graphics.',
    relatedTools: ['qr-generator', 'color-picker'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'color-picker',
    name: 'Color Picker & Palette',
    description: 'Inspect HEX/RGB/HSL values and generate harmonies or palette variations.',
    category: 'converter',
    tags: ['color picker', 'palette generator', 'harmonies', 'hex code', 'rgb converter'],
    keywords: ['color picker online', 'palette generator', 'hex rgb hsl converter', 'color harmony finder'],
    icon: 'Sliders',
    seoTitle: 'Free Client-Side Color Picker & Palette Generator',
    seoDescription: 'Choose colors and inspect HEX, RGB, and HSL values. Generate analogous, complementary, triadic, and monochromatic color palettes.',
    relatedTools: ['qr-generator', 'barcode-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert metric and imperial units for Length, Weight, Temperature, and Speed.',
    category: 'converter',
    tags: ['unit converter', 'conversion', 'metric imperial', 'length converter', 'weight converter'],
    keywords: ['unit converter online', 'metric to imperial conversion', 'celsius to fahrenheit', 'convert kg to lbs'],
    icon: 'Ruler',
    seoTitle: 'Free Universal Unit Converter - Length, Weight & Temperature',
    seoDescription: 'Convert units for length, weight, area, volume, time, speed, and temperature locally. Instant metric-imperial conversions.',
    relatedTools: ['color-picker', 'pomodoro-timer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
];
