export interface ToolEntry {
  id: string; // Dynamic URL slug matching the folder name
  name: string; // Human display name
  description: string; // Short UI description
  category: 'pdf' | 'image' | 'developer' | 'text' | 'calculator' | 'converter';
  tags: string[]; // Search tags/aliases
  keywords: string[]; // Meta tags
  icon: 'FileText' | 'Image' | 'Terminal' | 'Hash' | 'Calculator' | 'RefreshCw' | 'Sliders' | 'Code' | 'List' | 'Key' | 'Calendar' | 'Scale';
  seoTitle: string; // SEO page title
  seoDescription: string; // SEO meta description
  relatedTools: string[]; // Related tool IDs for recommendations
  requirements: {
    browser: boolean;
    server: boolean;
  };
  featured?: boolean;
  popular?: boolean;
  addedAt: string; // ISO date string (YYYY-MM-DD)
  status: 'draft' | 'planned' | 'in-development' | 'testing' | 'published' | 'maintenance';
}

export const TOOLS_REGISTRY: ToolEntry[] = [
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate RFC4122 version 4 compliant universally unique identifiers (UUIDs) locally.',
    category: 'developer',
    tags: ['uuid', 'guid', 'generator', 'random', 'unique', 'rfc4122'],
    keywords: ['uuid generator', 'generate uuid', 'guid generator', 'random uuid', 'online uuid'],
    icon: 'Key',
    seoTitle: 'Free Client-Side UUID & GUID Generator',
    seoDescription: 'Generate RFC4122 v4 compliant universally unique identifiers (UUIDs) or GUIDs locally in your browser. Complete data privacy.',
    relatedTools: ['base64-converter', 'json-formatter'],
    requirements: { browser: true, server: false },
    featured: true,
    popular: true,
    addedAt: '2026-06-25',
    status: 'published',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Pretty-print, validate, minify, and check syntax of your JSON code.',
    category: 'developer',
    tags: ['json', 'formatter', 'pretty print', 'minify', 'validator', 'beautify'],
    keywords: ['json formatter', 'pretty print json', 'format json online', 'minify json', 'validate json'],
    icon: 'Code',
    seoTitle: 'Free Client-Side JSON Formatter & Beautifier',
    seoDescription: 'Pretty-print, minify, and validate JSON code securely in your web browser. Zero server uploads for complete data privacy.',
    relatedTools: ['uuid-generator', 'base64-converter'],
    requirements: { browser: true, server: false },
    featured: true,
    popular: true,
    addedAt: '2026-06-01',
    status: 'published',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Analyze word count, character size, read time, and text stats in real-time.',
    category: 'text',
    tags: ['word count', 'character count', 'analyzer', 'text stats', 'casing'],
    keywords: ['word counter', 'character counter', 'word count online', 'character size analyzer'],
    icon: 'List',
    seoTitle: 'Free Online Word Counter - Analyze Text & Character Size',
    seoDescription: 'Count words, characters, sentences, paragraphs, and read times. Secure, in-browser analysis with no data logged.',
    relatedTools: ['uuid-generator', 'password-generator'],
    requirements: { browser: true, server: false },
    featured: true,
    addedAt: '2026-06-10',
    status: 'published',
  },
  {
    id: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Convert text, strings, and images into Base64 format and back.',
    category: 'developer',
    tags: ['base64', 'encode', 'decode', 'converter', 'string', 'binary'],
    keywords: ['base64 encoder', 'base64 decoder', 'base64 encode online', 'base64 convert string'],
    icon: 'Key',
    seoTitle: 'Free Client-Side Base64 Encoder & Decoder',
    seoDescription: 'Encode and decode Base64 strings and files safely. 100% browser-based calculations protect sensitive tokens.',
    relatedTools: ['uuid-generator', 'json-formatter'],
    requirements: { browser: true, server: false },
    popular: true,
    addedAt: '2026-06-15',
    status: 'published',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL parameters safely and instantly.',
    category: 'developer',
    tags: ['url', 'encode', 'decode', 'uri', 'parameter', 'percent-encoding'],
    keywords: ['url encoder', 'url decoder', 'urlencode online', 'decode url parameter'],
    icon: 'Code',
    seoTitle: 'Free Client-Side URL Parameter Encoder & Decoder',
    seoDescription: 'Encode and decode URL parameters or URI strings securely in your browser tab. Instant offline client-side conversions.',
    relatedTools: ['json-formatter', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-27',
    status: 'published',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate highly secure custom passwords locally using custom strength rules.',
    category: 'developer',
    tags: ['password', 'generator', 'security', 'random string', 'passphrase'],
    keywords: ['password generator', 'random password', 'generate secure password', 'online password maker'],
    icon: 'Key',
    seoTitle: 'Free Client-Side Secure Password Generator',
    seoDescription: 'Generate secure, randomized passwords locally in your browser. Configure character rules, lengths, and avoid server storage logs.',
    relatedTools: ['uuid-generator', 'base64-converter'],
    requirements: { browser: true, server: false },
    featured: true,
    addedAt: '2026-06-27',
    status: 'published',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JSON Web Tokens (JWT) locally to view header, payload, and claim dates.',
    category: 'developer',
    tags: ['jwt', 'token', 'decoder', 'json web token', 'payload'],
    keywords: ['jwt decoder', 'decode jwt online', 'jwt payload viewer', 'jwt header'],
    icon: 'Key',
    seoTitle: 'Free Client-Side JWT Decoder & Viewer',
    seoDescription: 'Decode JSON Web Tokens (JWT) locally in your browser. View header, payload claims, expiration states, and signature components securely.',
    relatedTools: ['uuid-generator', 'json-formatter', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes locally.',
    category: 'developer',
    tags: ['hash', 'crypto', 'sha256', 'md5', 'sha512', 'checksum'],
    keywords: ['hash generator', 'md5 hash generator', 'sha256 online generator', 'generate hash locally'],
    icon: 'Hash',
    seoTitle: 'Free Client-Side MD5, SHA-256 & SHA-512 Hash Generator',
    seoDescription: 'Calculate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 cryptographic hashes or checksums securely in your browser using Web Crypto APIs.',
    relatedTools: ['uuid-generator', 'base64-converter', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text casing style between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, and other formats locally.',
    category: 'text',
    tags: ['case converter', 'text casing', 'uppercase', 'lowercase', 'camelcase', 'pascalcase', 'slugify'],
    keywords: ['case converter', 'convert text case', 'slugify string online', 'uppercase lowercase converter'],
    icon: 'List',
    seoTitle: 'Free Client-Side Text Case Converter - UPPERCASE, camelCase & PascalCase',
    seoDescription: 'Convert your text casing style between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case securely in your browser tab.',
    relatedTools: ['word-counter', 'uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Clean list data by removing duplicate lines. Supports case sensitivity filters, sorting, and whitespace trimming.',
    category: 'text',
    tags: ['duplicate lines', 'remove duplicates', 'deduplicate list', 'sort list', 'unique list'],
    keywords: ['remove duplicate lines', 'deduplicate list online', 'remove repeating lines', 'clean text list'],
    icon: 'List',
    seoTitle: 'Free Client-Side List Deduplicator - Remove Duplicate Lines',
    seoDescription: 'Clean your list data by removing duplicate lines securely in your browser. Configure case-sensitive compares, whitespace trims, and alphabetical sorting.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate custom placeholder text in words, sentences, or paragraphs formatted as plain text or HTML.',
    category: 'text',
    tags: ['lorem ipsum', 'placeholder text', 'dummy text', 'text generator', 'html generator'],
    keywords: ['lorem ipsum generator', 'generate placeholder text', 'dummy paragraph creator', 'free lorem text'],
    icon: 'List',
    seoTitle: 'Free Client-Side Lorem Ipsum Placeholder Text Generator',
    seoDescription: 'Generate custom dummy text in words, sentences, or paragraphs, formatted as plain text or HTML paragraph tags securely in your browser tab.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Increase productivity using the Pomodoro technique. Keep focus, manage breaks, and track your daily sessions locally.',
    category: 'calculator',
    tags: ['pomodoro', 'timer', 'focus timer', 'productivity timer', 'pomodoro technique', 'time management'],
    keywords: ['pomodoro timer', 'online pomodoro', 'focus countdown', 'productivity timer online', 'pomodoro clock'],
    icon: 'Calculator',
    seoTitle: 'Free Client-Side Pomodoro Focus Timer - Boost Productivity',
    seoDescription: 'Boost your focus and time management using the Pomodoro technique. Custom focus slots, short/long breaks, fullscreen countdown mode, alerts, and browser notifications.',
    relatedTools: ['word-counter', 'uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate duration between dates or add/subtract calendar days.',
    category: 'calculator',
    tags: ['date', 'time duration', 'calendar calculator', 'days between dates'],
    keywords: ['date calculator', 'calculate days between dates', 'add days to date', 'calendar duration calculator'],
    icon: 'Calendar',
    seoTitle: 'Free Online Date & Time Calculator',
    seoDescription: 'Calculate the exact number of days, weeks, months, or years between two calendar dates, or add/subtract days in your browser.',
    relatedTools: ['uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-20',
    status: 'planned',
  },
];
