import { IconName } from '@/components/shared/Icon';

export interface ToolEntry {
  id: string; // Dynamic URL slug matching the folder name
  name: string; // Human display name
  description: string; // Short UI description
  category: 'pdf' | 'image' | 'developer' | 'text' | 'calculator' | 'converter' | 'live-data';
  type?: 'local' | 'api';
  tags: string[]; // Search tags/aliases
  keywords: string[]; // Meta tags
  icon: IconName;
  seoTitle: string; // SEO page title
  seoDescription: string; // SEO meta description
  relatedTools: string[]; // Related tool IDs for recommendations
  requirements: {
    browser: boolean;
    server: boolean;
  };
  addedAt: string; // ISO date string (YYYY-MM-DD)
  status: 'draft' | 'planned' | 'in-development' | 'testing' | 'published' | 'maintenance';
  qualityTier?: 'flagship' | 'supporting' | 'basic';
  noindex?: boolean;
}

export const TOOLS_REGISTRY: ToolEntry[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, pretty-print, validate, and minify JSON data with diagnostic error tracking.',
    category: 'developer',
    tags: ['json', 'formatter', 'pretty print', 'minify', 'validator', 'beautify'],
    keywords: ['json formatter', 'pretty print json', 'format json', 'minify json', 'json beautifier'],
    icon: 'Braces',
    seoTitle: 'JSON Formatter, Beautifier & Minifier',
    seoDescription: 'Format, validate, and minify JSON directly in your browser. View syntax error locations, copy formatted output, and export files without sending data to a server.',
    relatedTools: ['json-validator', 'unicode-inspector', 'base64-converter', 'jwt-decoder'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-01',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Check JSON syntax validity, pinpoint matching brackets, and diagnose syntax errors.',
    category: 'developer',
    tags: ['json', 'validator', 'syntax check', 'lint json', 'json schema'],
    keywords: ['json validator', 'validate json', 'json syntax checker', 'lint json file'],
    icon: 'Code',
    seoTitle: 'JSON Validator & Syntax Error Checker',
    seoDescription: 'Validate JSON syntax compliance against RFC 8259 directly in your browser. Pinpoint exact error line numbers, column offsets, and trailing commas.',
    relatedTools: ['json-formatter', 'unicode-inspector', 'base64-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-02',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) locally to view header, payload claims, and dates.',
    category: 'developer',
    tags: ['jwt', 'token', 'decoder', 'json web token', 'payload', 'claims'],
    keywords: ['jwt decoder', 'decode jwt', 'jwt payload viewer', 'jwt inspector', 'jwt token claims'],
    icon: 'Key',
    seoTitle: 'JWT Decoder & Token Claim Inspector',
    seoDescription: 'Decode JSON Web Tokens (JWT) locally in your browser. Inspect header parameters, payload claims, and expiration timestamps without transmitting tokens to a server.',
    relatedTools: ['base64-converter', 'json-formatter', 'timestamp-explorer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'unicode-inspector',
    name: 'Unicode Inspector',
    description: 'Inspect Unicode code points, UTF-8 bytes, UTF-16 units, and detect zero-width characters.',
    category: 'developer',
    tags: ['unicode', 'code point', 'utf8', 'utf16', 'zero-width', 'character inspector', 'hex'],
    keywords: ['unicode inspector', 'inspect unicode characters', 'zero width space detector', 'utf8 byte viewer', 'code point lookup'],
    icon: 'Code',
    seoTitle: 'Unicode Inspector & Character Code Point Analyzer',
    seoDescription: 'Inspect character code points, UTF-8 byte sequences, UTF-16 code units, categories, zero-width spaces, and bidirectional control characters in your browser.',
    relatedTools: ['json-formatter', 'base64-converter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-15',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'timestamp-explorer',
    name: 'Timestamp Explorer',
    description: 'Convert Unix epoch timestamps in seconds and milliseconds to ISO 8601, RFC 3339, and local dates.',
    category: 'developer',
    tags: ['timestamp', 'epoch', 'unix', 'date', 'iso8601', 'rfc3339', 'converter'],
    keywords: ['timestamp converter', 'unix epoch converter', 'epoch to date', 'iso 8601 timestamp', 'unix seconds milliseconds'],
    icon: 'Clock',
    seoTitle: 'Unix Timestamp & Epoch Converter',
    seoDescription: 'Convert Unix epoch timestamps in seconds and milliseconds to ISO 8601, RFC 3339, RFC 2822, UTC, and local date formats directly in your browser.',
    relatedTools: ['jwt-decoder', 'uuid-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-15',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes locally.',
    category: 'developer',
    tags: ['hash', 'crypto', 'sha256', 'md5', 'sha512', 'checksum', 'digest'],
    keywords: ['hash generator', 'sha256 generator', 'md5 checksum', 'sha512 hash', 'crypto digest generator'],
    icon: 'Hash',
    seoTitle: 'Cryptographic Hash Generator & Checksum Calculator',
    seoDescription: 'Calculate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 cryptographic hashes and checksums directly in your browser using the Web Crypto API.',
    relatedTools: ['base64-converter', 'uuid-generator', 'password-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-28',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Convert text, strings, and files into Base64 format and back.',
    category: 'developer',
    tags: ['base64', 'encode', 'decode', 'converter', 'string', 'binary'],
    keywords: ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode string', 'base64 binary converter'],
    icon: 'Binary',
    seoTitle: 'Base64 Encoder & Decoder',
    seoDescription: 'Encode and decode Base64 strings and files safely in your browser. All calculations run locally to protect sensitive tokens.',
    relatedTools: ['jwt-decoder', 'hash-generator', 'url-encoder'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-15',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF documents into a single document with custom page ordering.',
    category: 'pdf',
    tags: ['pdf', 'merge', 'combine', 'join', 'pdf documents', 'reorder'],
    keywords: ['pdf merge', 'merge pdf files', 'combine pdfs', 'join pdf documents', 'merge pdf locally'],
    icon: 'FileText',
    seoTitle: 'PDF Merge - Combine PDF Documents Locally',
    seoDescription: 'Combine multiple PDF documents into a single file directly in your browser. Reorder pages before merging with zero server uploads.',
    relatedTools: ['pdf-split', 'pdf-compress', 'images-to-pdf'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-01',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    description: 'Split PDF files by pages, extract specific ranges, or export individual pages.',
    category: 'pdf',
    tags: ['pdf', 'split', 'extract', 'pages', 'cut', 'separate'],
    keywords: ['pdf split', 'split pdf pages', 'extract pdf pages', 'separate pdf', 'split pdf locally'],
    icon: 'FileText',
    seoTitle: 'PDF Splitter - Extract PDF Pages Locally',
    seoDescription: 'Split PDF files by pages, extract specific page ranges, or export individual pages locally in your browser without uploading documents.',
    relatedTools: ['pdf-merge', 'pdf-compress', 'images-to-pdf'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-02',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    description: 'Compress and optimize PDF file sizes locally using Ghostscript WebAssembly.',
    category: 'pdf',
    tags: ['pdf', 'compress', 'optimize', 'shrink', 'ghostscript', 'wasm', 'reduce size'],
    keywords: ['pdf compress', 'compress pdf', 'reduce pdf size', 'pdf optimizer', 'offline pdf compressor'],
    icon: 'FileText',
    seoTitle: 'PDF Compressor - Reduce PDF Size with WebAssembly',
    seoDescription: 'Compress and optimize PDF file sizes locally in your browser using Ghostscript WebAssembly with zero server uploads.',
    relatedTools: ['pdf-merge', 'pdf-split', 'images-to-pdf'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-20',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate RFC 4122 version 4 compliant universally unique identifiers (UUIDs) locally.',
    category: 'developer',
    tags: ['uuid', 'guid', 'generator', 'random', 'unique', 'rfc4122'],
    keywords: ['uuid generator', 'generate uuid', 'guid generator', 'random uuid', 'rfc 4122 uuid'],
    icon: 'Fingerprint',
    seoTitle: 'UUID Generator - RFC 4122 v4 GUIDs',
    seoDescription: 'Generate RFC 4122 v4 compliant universally unique identifiers (UUIDs) or GUIDs locally in your browser using the Web Crypto API.',
    relatedTools: ['hash-generator', 'password-generator', 'timestamp-explorer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-25',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL parameters and URI components safely and instantly.',
    category: 'developer',
    tags: ['url', 'encode', 'decode', 'uri', 'parameter', 'percent-encoding'],
    keywords: ['url encoder', 'url decoder', 'urlencode', 'decode url parameter', 'percent encoding'],
    icon: 'RefreshCw',
    seoTitle: 'URL Encoder & Decoder - URI Component Encoding',
    seoDescription: 'Encode and decode URL parameters and URI strings securely in your browser tab with instant client-side conversions.',
    relatedTools: ['base64-converter', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-27',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress and optimize JPEG, PNG, and WebP images locally to reduce file sizes.',
    category: 'image',
    tags: ['image', 'compress', 'optimize', 'shrink', 'jpeg', 'png', 'webp'],
    keywords: ['image compressor', 'compress image', 'reduce image size', 'optimize image', 'compress png jpeg webp'],
    icon: 'Image',
    seoTitle: 'Image Compressor - Optimize JPEG, PNG & WebP',
    seoDescription: 'Compress and optimize JPEG, PNG, and WebP image file sizes locally in your browser using HTML5 Canvas with real-time size reduction previews.',
    relatedTools: ['image-resizer', 'image-format-converter', 'image-cropper'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-05',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize image dimensions in pixels with aspect ratio locking client-side.',
    category: 'image',
    tags: ['image', 'resize', 'scale', 'dimensions', 'width', 'height', 'aspect ratio'],
    keywords: ['image resizer', 'resize image', 'scale image', 'image dimensions', 'resize photo'],
    icon: 'Sliders',
    seoTitle: 'Image Resizer - Scale Pixel Dimensions',
    seoDescription: 'Resize image dimensions with aspect ratio locking directly in your browser. Supports JPEG, PNG, and WebP formats.',
    relatedTools: ['image-compressor', 'image-format-converter', 'image-cropper'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-06',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'image-format-converter',
    name: 'Image Format Converter',
    description: 'Convert images between PNG, JPEG, and WebP formats client-side.',
    category: 'image',
    tags: ['image', 'convert', 'format', 'png', 'jpeg', 'jpg', 'webp'],
    keywords: ['image converter', 'png to jpeg', 'jpeg to webp', 'png to webp', 'convert image format'],
    icon: 'Layers',
    seoTitle: 'Image Format Converter - PNG, JPEG & WebP',
    seoDescription: 'Convert images seamlessly between PNG, JPEG, and WebP formats directly in your browser with zero server uploads.',
    relatedTools: ['image-compressor', 'image-resizer', 'image-cropper'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-07',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to custom rectangular areas and aspect ratios directly in your browser.',
    category: 'image',
    tags: ['image', 'crop', 'trim', 'aspect ratio', 'cut'],
    keywords: ['image cropper', 'crop image', 'crop photo', 'trim image', 'crop picture'],
    icon: 'Crop',
    seoTitle: 'Image Cropper - Crop Photos & Images Locally',
    seoDescription: 'Crop image files to custom rectangular areas and aspect ratios securely in your browser with lossless pixel precision.',
    relatedTools: ['image-resizer', 'image-compressor', 'image-format-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-08',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Compile multiple PNG, JPEG, and WebP images into a single PDF document.',
    category: 'pdf',
    tags: ['images to pdf', 'jpg to pdf', 'png to pdf', 'convert photos to pdf', 'compile'],
    keywords: ['images to pdf', 'jpg to pdf', 'png to pdf', 'convert images to pdf', 'combine photos into pdf'],
    icon: 'FileImage',
    seoTitle: 'Images to PDF - Convert Photos to PDF Locally',
    seoDescription: 'Compile PNG, JPEG, and WebP images into a single PDF document directly in your browser with custom page ordering.',
    relatedTools: ['pdf-merge', 'pdf-split', 'pdf-compress'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-03',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords locally using CSPRNG entropy rules.',
    category: 'developer',
    tags: ['password', 'generator', 'security', 'random string', 'passphrase', 'csprng'],
    keywords: ['password generator', 'random password', 'generate password', 'csprng password'],
    icon: 'Lock',
    seoTitle: 'Random Password Generator - Web Crypto CSPRNG',
    seoDescription: 'Generate randomized passwords locally in your browser using the Web Crypto API. Configure character pools, lengths, and avoid server storage logs.',
    relatedTools: ['uuid-generator', 'hash-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-27',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate customizable, high-resolution QR codes from text or URL parameters.',
    category: 'developer',
    tags: ['qr', 'code', 'generator', 'barcode', '2d', 'matrix'],
    keywords: ['qr code generator', 'generate qr code', 'make qr code', 'custom qr code'],
    icon: 'QrCode',
    seoTitle: 'QR Code Generator - Custom Colors & High Resolution',
    seoDescription: 'Create customizable QR codes from text or URL parameters instantly in your browser and download high-resolution PNGs.',
    relatedTools: ['barcode-generator', 'url-encoder'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-15',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate CODE128, EAN-13, EAN-8, and UPC-A barcodes as scalable vector SVGs.',
    category: 'developer',
    tags: ['barcode', 'generator', 'code128', 'ean13', 'upc', 'vector', 'svg'],
    keywords: ['barcode generator', 'generate barcode', 'code128 generator', 'ean13 barcode', 'vector barcode'],
    icon: 'Barcode',
    seoTitle: 'Vector Barcode Generator - CODE128, EAN & UPC',
    seoDescription: 'Generate standard CODE128, EAN-13, EAN-8, and UPC-A barcodes as scalable vector SVGs directly in your browser.',
    relatedTools: ['qr-generator'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-16',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors, inspect HSL/RGB/HEX values, and generate color harmonies.',
    category: 'developer',
    tags: ['color', 'picker', 'palette', 'hex', 'rgb', 'hsl', 'harmonies'],
    keywords: ['color picker', 'hex to rgb', 'hsl color picker', 'color palette generator', 'color harmonies'],
    icon: 'Sliders',
    seoTitle: 'Color Picker & Palette Harmony Explorer',
    seoDescription: 'Inspect and convert colors between HEX, RGB, and HSL color models, test contrast ratios, and generate complementary palettes in your browser.',
    relatedTools: ['case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-17',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Analyze word count, character size, read time, and text stats in real-time.',
    category: 'text',
    tags: ['word count', 'character count', 'analyzer', 'text stats', 'reading time'],
    keywords: ['word counter', 'character counter', 'word count', 'text analyzer', 'reading time calculator'],
    icon: 'CaseSensitive',
    seoTitle: 'Word Counter & Text Statistics Analyzer',
    seoDescription: 'Count words, characters, sentences, paragraphs, and estimated reading times directly in your browser with zero data logged.',
    relatedTools: ['case-converter', 'remove-duplicate-lines'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-10',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text case formatting between UPPERCASE, lowercase, camelCase, snake_case, and more.',
    category: 'text',
    tags: ['case', 'converter', 'uppercase', 'lowercase', 'camelcase', 'snake_case', 'kebab-case'],
    keywords: ['case converter', 'text case', 'camelcase converter', 'snake case', 'uppercase to lowercase'],
    icon: 'Type',
    seoTitle: 'Text Case Converter - Camel, Snake, Kebab & Title Case',
    seoDescription: 'Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case directly in your browser.',
    relatedTools: ['word-counter', 'remove-duplicate-lines'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-29',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Filter duplicate lines from text lists with whitespace and case options.',
    category: 'text',
    tags: ['duplicate', 'lines', 'remover', 'cleaner', 'deduplicate', 'list'],
    keywords: ['remove duplicate lines', 'deduplicate list', 'line deduplicator', 'clean list', 'unique lines'],
    icon: 'List',
    seoTitle: 'Duplicate Line Remover - List Deduplication',
    seoDescription: 'Filter repeating rows and duplicate lines from lists and datasets with configurable case sensitivity, whitespace trimming, and sorting.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-06-30',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert values across Metric and Imperial measurement units for length, weight, area, and more.',
    category: 'converter',
    tags: ['unit', 'converter', 'metric', 'imperial', 'length', 'weight', 'temperature', 'volume'],
    keywords: ['unit converter', 'metric to imperial', 'length converter', 'weight converter', 'measurement converter'],
    icon: 'Scale',
    seoTitle: 'Universal Unit Converter - Metric & Imperial',
    seoDescription: 'Convert values across Metric and Imperial measurement units for Length, Weight, Temperature, Area, Volume, Time, and Speed directly in your browser.',
    relatedTools: ['timestamp-explorer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-18',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Productivity focus timer with customizable work intervals, short breaks, and audio chimes.',
    category: 'calculator',
    tags: ['pomodoro', 'timer', 'focus', 'productivity', 'study', 'work intervals'],
    keywords: ['pomodoro timer', 'focus timer', 'productivity timer', 'pomodoro clock', 'study timer'],
    icon: 'Timer',
    seoTitle: 'Pomodoro Timer & Focus Workstation',
    seoDescription: 'Structure work and study sessions with the Pomodoro technique using customizable focus intervals, short breaks, long breaks, and Web Audio alert chimes.',
    relatedTools: ['stopwatch', 'countdown-timer', 'fullscreen-clock'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-01',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    description: 'Track elapsed duration with split laps using high-resolution performance timers.',
    category: 'calculator',
    tags: ['stopwatch', 'timer', 'lap', 'splits', 'performance timer'],
    keywords: ['stopwatch', 'online stopwatch', 'lap timer', 'split timer', 'precision stopwatch'],
    icon: 'Clock',
    seoTitle: 'Stopwatch & Lap Timer - High-Resolution Timing',
    seoDescription: 'Track elapsed time and record lap splits with high-resolution accuracy in your browser using performance.now() timers.',
    relatedTools: ['pomodoro-timer', 'countdown-timer', 'fullscreen-clock'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-10',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Set countdown durations with synthesized Web Audio completion alarm chimes.',
    category: 'calculator',
    tags: ['countdown', 'timer', 'alarm', 'clock'],
    keywords: ['countdown timer', 'timer with alarm', 'online countdown', 'set timer'],
    icon: 'Hourglass',
    seoTitle: 'Countdown Timer with Audio Alarm',
    seoDescription: 'Configure countdown timers with custom hours, minutes, and synthesized Web Audio completion alarms directly in your browser.',
    relatedTools: ['pomodoro-timer', 'stopwatch', 'fullscreen-clock'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-12',
    status: 'published',
    qualityTier: 'basic',
  },
  {
    id: 'fullscreen-clock',
    name: 'Fullscreen Clock',
    description: 'Fullscreen digital clock display with 12/24 hour modes for study desks and monitors.',
    category: 'calculator',
    tags: ['clock', 'digital clock', 'fullscreen', 'time', 'desk clock'],
    keywords: ['fullscreen clock', 'digital clock', 'desk clock', 'online clock', 'study clock'],
    icon: 'Clock',
    seoTitle: 'Fullscreen Digital Clock & Desk Display',
    seoDescription: 'Digital clock for study desks, focus spaces, and fullscreens with 12/24 hour options and date formatting.',
    relatedTools: ['pomodoro-timer', 'stopwatch'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-09',
    status: 'published',
    qualityTier: 'basic',
    noindex: true,
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate dummy placeholder text by words, sentences, or paragraphs for design mockups.',
    category: 'text',
    tags: ['lorem ipsum', 'placeholder', 'dummy text', 'filler text', 'generator'],
    keywords: ['lorem ipsum generator', 'dummy text generator', 'placeholder text', 'lorem ipsum'],
    icon: 'FileText',
    seoTitle: 'Lorem Ipsum Placeholder Text Generator',
    seoDescription: 'Generate custom dummy placeholder text in words, sentences, or paragraphs formatted as plain text or HTML tags.',
    relatedTools: ['word-counter', 'case-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-07-01',
    status: 'published',
    qualityTier: 'basic',
    noindex: true,
  },
  {
    id: 'github-explorer',
    name: 'GitHub Explorer',
    description: 'Inspect public GitHub repositories, stars, forks, open issues, and developer profiles.',
    category: 'live-data',
    type: 'api',
    tags: ['github', 'repository', 'repo', 'stars', 'forks', 'git', 'profile', 'developer'],
    keywords: ['github explorer', 'inspect github repo', 'github user lookup', 'github stats viewer'],
    icon: 'Code',
    seoTitle: 'GitHub Explorer - Inspect Repositories & User Profiles',
    seoDescription: 'Inspect public GitHub repositories, latest releases, star counts, and user metrics directly in your browser via the GitHub REST API.',
    relatedTools: ['jwt-decoder', 'http-status-explorer', 'json-formatter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'flagship',
  },
  {
    id: 'weather-forecast',
    name: 'Weather Forecast',
    description: 'Real-time global weather metrics, temperatures, wind speed, and atmospheric conditions.',
    category: 'live-data',
    type: 'api',
    tags: ['weather', 'forecast', 'temperature', 'climate', 'wind', 'humidity', 'meteorology'],
    keywords: ['weather forecast', 'live weather', 'check weather online', 'open meteo forecast'],
    icon: 'CloudSun',
    seoTitle: 'Live Weather Forecast - Global Meteorological Metrics',
    seoDescription: 'Search live global weather conditions, temperatures, wind speeds, and relative humidity powered by Open-Meteo public APIs.',
    relatedTools: ['country-info', 'public-holidays'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert world currencies with official daily exchange rates from the European Central Bank.',
    category: 'live-data',
    type: 'api',
    tags: ['currency', 'converter', 'exchange rates', 'forex', 'usd', 'eur', 'money', 'finance'],
    keywords: ['currency converter', 'live exchange rates', 'convert usd to eur', 'ecb exchange rates'],
    icon: 'Coins',
    seoTitle: 'Live Currency Converter - ECB Official Exchange Rates',
    seoDescription: 'Convert global currencies in real time using official daily European Central Bank exchange rates via the Frankfurter API.',
    relatedTools: ['unit-converter', 'country-info'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'country-info',
    name: 'Country Information',
    description: 'Explore country profiles, populations, official languages, currencies, and geographical regions.',
    category: 'live-data',
    type: 'api',
    tags: ['country', 'nations', 'geography', 'population', 'capital', 'languages', 'world'],
    keywords: ['country info', 'country profile lookup', 'world countries data', 'capital cities lookup'],
    icon: 'Globe',
    seoTitle: 'Country Profiles & Worldwide Geographical Information',
    seoDescription: 'Inspect country profiles, populations, capital cities, timezones, and currencies worldwide powered by the REST Countries API.',
    relatedTools: ['weather-forecast', 'public-holidays', 'currency-converter'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'public-holidays',
    name: 'Public Holidays',
    description: 'Browse national and bank holidays across 100+ countries by year with official observance dates.',
    category: 'live-data',
    type: 'api',
    tags: ['holidays', 'public holidays', 'bank holidays', 'calendar', 'national holidays', 'observance'],
    keywords: ['public holidays calendar', 'bank holidays lookup', 'national holidays by country', 'nager date holidays'],
    icon: 'CalendarDays',
    seoTitle: 'Worldwide Public & Bank Holidays Calendar',
    seoDescription: 'Explore national public holidays and bank observances across 100+ countries by year using the Nager.Date worldwide API.',
    relatedTools: ['country-info', 'timestamp-explorer', 'weather-forecast'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'astronomy-picture',
    name: 'Astronomy Picture of the Day',
    description: 'Official NASA daily astronomical photography, deep-space imagery, and astrophysical explanations.',
    category: 'live-data',
    type: 'api',
    tags: ['nasa', 'space', 'astronomy', 'apod', 'cosmos', 'universe', 'photography'],
    keywords: ['nasa apod', 'astronomy picture of the day', 'nasa space photography', 'astronomy image'],
    icon: 'Sparkles',
    seoTitle: 'NASA Astronomy Picture of the Day (APOD)',
    seoDescription: 'Explore daily deep-space cosmic photography and astrophysical context directly from NASA official open data APIs.',
    relatedTools: ['weather-forecast', 'http-status-explorer'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'supporting',
  },
  {
    id: 'http-status-explorer',
    name: 'HTTP Status Explorer',
    description: 'Lookup IETF RFC 9110 HTTP status codes, meanings, developer recovery actions, and response headers.',
    category: 'developer',
    type: 'local',
    tags: ['http', 'status code', '404', '500', '200', 'rfc9110', 'rest api', 'debugging', 'headers'],
    keywords: ['http status codes', 'http 404 meaning', 'http 502 bad gateway', 'rfc 9110 status codes'],
    icon: 'Server',
    seoTitle: 'HTTP Status Code & Response Header Explorer',
    seoDescription: 'Search and inspect IETF RFC 9110 HTTP status codes, caching behaviors, and actionable developer troubleshooting steps.',
    relatedTools: ['jwt-decoder', 'json-validator', 'url-encoder'],
    requirements: { browser: true, server: false },
    addedAt: '2026-08-30',
    status: 'published',
    qualityTier: 'flagship',
  }
];
