export interface HttpStatusEntry {
  code: number;
  phrase: string;
  category: '1xx' | '2xx' | '3xx' | '4xx' | '5xx';
  categoryName: string;
  description: string;
  developerAction: string;
  spec: string;
  cacheable: boolean;
}

export const HTTP_STATUSES: HttpStatusEntry[] = [
  {
    code: 200,
    phrase: 'OK',
    category: '2xx',
    categoryName: 'Success',
    description: 'The standard response for successful HTTP requests. The actual payload returned depends on the request method (GET returns representation, POST returns action result).',
    developerAction: 'Standard success response. Ensure appropriate Cache-Control headers are attached for caching.',
    spec: 'RFC 9110 Section 15.3.1',
    cacheable: true,
  },
  {
    code: 201,
    phrase: 'Created',
    category: '2xx',
    categoryName: 'Success',
    description: 'The request has succeeded and led to the creation of a new resource. The new resource URI is typically returned in the Location header.',
    developerAction: 'Return after successful REST POST mutations. Include Location header pointing to the newly created entity.',
    spec: 'RFC 9110 Section 15.3.2',
    cacheable: false,
  },
  {
    code: 204,
    phrase: 'No Content',
    category: '2xx',
    categoryName: 'Success',
    description: 'The server has fulfilled the request but does not need to return an entity-body. Commonly returned for DELETE actions or PUT updates without returned state.',
    developerAction: 'Ensure no response body or Content-Length payload is emitted with this code.',
    spec: 'RFC 9110 Section 15.3.5',
    cacheable: false,
  },
  {
    code: 301,
    phrase: 'Moved Permanently',
    category: '3xx',
    categoryName: 'Redirection',
    description: 'The requested resource has been assigned a new permanent URI. Search engines will transfer SEO ranking to the new target Location.',
    developerAction: 'Include a Location header with the new canonical target. Use for permanent domain and route migrations.',
    spec: 'RFC 9110 Section 15.4.2',
    cacheable: true,
  },
  {
    code: 302,
    phrase: 'Found (Temporary Redirect)',
    category: '3xx',
    categoryName: 'Redirection',
    description: 'The resource resides temporarily under a different URI. Clients should continue using the original URI for future requests.',
    developerAction: 'Use for transient redirects such as post-login redirects or temporary maintenance pages.',
    spec: 'RFC 9110 Section 15.4.3',
    cacheable: false,
  },
  {
    code: 304,
    phrase: 'Not Modified',
    category: '3xx',
    categoryName: 'Redirection',
    description: 'Indicates that the resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match (ETag).',
    developerAction: 'Emit when client cache validators match current entity state. Do not include a message body.',
    spec: 'RFC 9110 Section 15.4.5',
    cacheable: true,
  },
  {
    code: 400,
    phrase: 'Bad Request',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The server cannot process the request due to perceived client errors (e.g., malformed request syntax, invalid query parameters, or deceptive routing).',
    developerAction: 'Validate client JSON schema and query payloads. Return descriptive validation error messages in the body.',
    spec: 'RFC 9110 Section 15.5.1',
    cacheable: false,
  },
  {
    code: 401,
    phrase: 'Unauthorized',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The request requires user authentication. The client must authenticate itself to receive the requested response.',
    developerAction: 'Return when Authorization header is missing or bearer token is invalid/expired. Include WWW-Authenticate challenge header.',
    spec: 'RFC 9110 Section 15.5.2',
    cacheable: false,
  },
  {
    code: 403,
    phrase: 'Forbidden',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The client does not have access rights to the content. Unlike 401, the client identity is known to the server, but authorization is denied.',
    developerAction: 'Return for RBAC role permission failures (e.g. standard user accessing admin endpoints). Do not prompt for re-authentication.',
    spec: 'RFC 9110 Section 15.5.4',
    cacheable: false,
  },
  {
    code: 404,
    phrase: 'Not Found',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The server cannot find the requested resource. May also be returned instead of 403 to hide the existence of a resource from an unauthorized client.',
    developerAction: 'Verify URL routing paths and database ID parameters. Return customized user-friendly 404 pages.',
    spec: 'RFC 9110 Section 15.5.5',
    cacheable: true,
  },
  {
    code: 405,
    phrase: 'Method Not Allowed',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The request method is recognized by the server but is not supported by the target resource (e.g., sending a POST to a read-only endpoint).',
    developerAction: 'Must include an Allow header in the response containing a list of valid methods (e.g., Allow: GET, HEAD).',
    spec: 'RFC 9110 Section 15.5.6',
    cacheable: false,
  },
  {
    code: 408,
    phrase: 'Request Timeout',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The server did not receive a complete request message within the time that it was prepared to wait.',
    developerAction: 'Check client network latency or long file upload socket disconnections.',
    spec: 'RFC 9110 Section 15.5.9',
    cacheable: false,
  },
  {
    code: 409,
    phrase: 'Conflict',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The request could not be completed due to a conflict with the current state of the target resource (e.g. edit conflicts in concurrent PUT requests or duplicate database unique constraints).',
    developerAction: 'Provide conflict resolution details in the response body so the client can merge or retry.',
    spec: 'RFC 9110 Section 15.5.10',
    cacheable: false,
  },
  {
    code: 422,
    phrase: 'Unprocessable Entity',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The server understands the content type of the request entity, and the syntax is correct, but was unable to process the contained instructions (semantic validation error).',
    developerAction: 'Standard response for REST payload field validation errors (e.g., missing required fields, invalid email format).',
    spec: 'RFC 9110 Section 15.5.21',
    cacheable: false,
  },
  {
    code: 429,
    phrase: 'Too Many Requests',
    category: '4xx',
    categoryName: 'Client Error',
    description: 'The user has sent too many requests in a given amount of time (rate limiting).',
    developerAction: 'Include a Retry-After header indicating how many seconds to wait before making a new request.',
    spec: 'RFC 6585 Section 4',
    cacheable: false,
  },
  {
    code: 500,
    phrase: 'Internal Server Error',
    category: '5xx',
    categoryName: 'Server Error',
    description: 'The server encountered an unexpected condition that prevented it from fulfilling the request.',
    developerAction: 'Inspect server application crash logs and unhandled exception traces. Avoid leaking stack traces in production responses.',
    spec: 'RFC 9110 Section 15.6.1',
    cacheable: false,
  },
  {
    code: 502,
    phrase: 'Bad Gateway',
    category: '5xx',
    categoryName: 'Server Error',
    description: 'The server, while acting as a gateway or proxy, received an invalid response from the inbound upstream server.',
    developerAction: 'Check proxy configurations (Nginx, Cloudflare, AWS ALB) and verify downstream application service health.',
    spec: 'RFC 9110 Section 15.6.3',
    cacheable: false,
  },
  {
    code: 503,
    phrase: 'Service Unavailable',
    category: '5xx',
    categoryName: 'Server Error',
    description: 'The server is currently unable to handle the request due to a temporary overload or scheduled maintenance.',
    developerAction: 'Emit during deployment drain or maintenance windows. Include a Retry-After header.',
    spec: 'RFC 9110 Section 15.6.4',
    cacheable: false,
  },
  {
    code: 504,
    phrase: 'Gateway Timeout',
    category: '5xx',
    categoryName: 'Server Error',
    description: 'The server, while acting as a gateway or proxy, did not receive a timely response from an upstream server.',
    developerAction: 'Increase upstream timeout limits or optimize slow database queries running in the backend application.',
    spec: 'RFC 9110 Section 15.6.5',
    cacheable: false,
  },
];
